task17=^\d+.?\d*([eE][-+]?\d+)?$
task18=^\d{3}[-\s]?\d{3}-\d{4}$
task19=^([a-zA-Z0-9_.]+)@.$
task20=<([a-zA-Z0-9]+)(?:\s.)?>>??
task21=^(.).(jpg|png|gif)$
task22=^\s(.+?)\s*$
task23=at\s+(\w+)((\w+.java:(\d+)
task24=^([a-z]+)://([a-zA-Z0-9.-]+(?::(\d+))??