task1=.*
task2=\d+
task3=\..$
task4=^[cmf]an$
task5=^[^b]og|hog|dog$
task6=^[A-C][a-c][a-c]$
task7=waz{3,6}up
task8=a+[abc]+
task9=\d+ files? found\?
task10=\d+\.\s+\w+|\d+\.\t+\w+|\d+\.\s+\w+
task11=^Mission: successful$
task12=^(file_record_transcript|file_\d+)\.pdf$
task13=^([A-Z][a-z]{2} (\d{4}))$
task14=^(\d+)x(\d+)$
task15=I love (cats|dogs)
task16=.*
